package tokenTest.Util;

public enum Status {
	OK(0),
	
	ERROR_GENERIC(-10086),
	ERROR_USER_NOT_FOUND(-2),
	ERROR_WRONG_TOKEN(-1000),
	ERROR_MAX_LOGIN_ATTEMPTS(-3),
	
	ERROR_INVALID_PHONE_NUMBER(-4),
	ERROR_PHONE_VALIDATION_FAIL(-5),
	
	ERROR_WRONG_VALIDATION_CODE(-6),
	
	ERROR_INVALID_PAGE_NUM(-7),
	ERROR_CANNOT_GET_LOCATION(-8),
	
	ERROR_CANNOT_DELETE_PROFILE_PHOTO(-9),
	
	ERROR_PIC_NOT_FOUND(-10),
	
	ERROR_INVALID_GENDER(-11),
	
	ERROR_INVALID_MEETING_STATUS(-12),
	
	ERROR_MEETING_NOT_FOUND(-13),
	
	ERROR_SHOP_NOT_FOUND(-14),
	
	ERROR_NO_CURRENT_MEETING(-15),
	
	ERROR_NO_SUCH_USER(-16),
	
	ERROR_NO_REQUEST_MADE(-17),
	
	ERROR_NO_REAPPLY(-19),
	
	ERROR_BANNED(-20),
	
	ERROR_NOT_BANNED(-21),
	
	SERVICE_NOT_AVAILABLE(-999);
	
	int value;
	public int getValue() {
		return value;
	}
	
	Status(int val){
		value = val;
	}
}
